version: "3.7"
services:
  ausy-app:
    build:
      args:
        user: tris
        uid: 1000
      context: ./
      dockerfile: ./docker/php/Dockerfile
    image: ausy
    container_name: ausy-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - backend

  ausy-db:
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password
    container_name: ausy-db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
    ports:
      - 33066:3306
    restart: unless-stopped

  ausy-nginx:
    image: nginx:alpine
    container_name: ausy-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - frontend
      - backend

volumes:
  mysql-data:

networks:
  frontend:
  backend:
