version: "3.7"
services:
  ausy-app:
    build:
      args:
        user: tris
        uid: 1000
      context: ./
      dockerfile: ./docker/php/Dockerfile
    image: ausy
    container_name: ausy-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - ausy

  ausy-db:
    image: mysql:8.0
    container_name: ausy-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - ausy

  ausy-nginx:
    image: nginx:alpine
    container_name: ausy-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - ausy

networks:
  ausy:
    driver: bridge
